/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData path_2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pay = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin__4_ = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reptiles_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search__1_ = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_pets_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user__3_ = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user__7_ = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bird_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cat_logo = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock__2_ = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog_icon = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish_icon = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_416 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart__1_ = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart__2_ = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home__1_ = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_run = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_inside = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout__1_ = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu__1_ = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cartfilled = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path_1 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
